# Generated by Django 2.1.8 on 2019-10-31 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0017_auto_20191026_1704'),
        ('bulletin_board', '0017_auto_20191028_1549'),
    ]

    operations = [
    ]
